version: '3.8'
services:
    nginx:
        container_name: nginx
        image: nginx:alpine
        ports:
            - "80:80"
        depends_on:
            - app
            - db
        volumes:
            - ./src:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d

    app:
        container_name: laravel
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www
        ports:
            - "8000:9000"
        working_dir: /var/www

    db:
        container_name: mysql
        image: mysql:8.0
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=systemir_laravel_shop
            - MYSQL_ROOT_PASSWORD=password

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "9000:80"
        depends_on:
            - db